
a="Aayush"
name= input("Enter your name: ")
print (f"Hello {name}")
print(a)
print(a[0])
print (a[0:4])
print(a[:4])
print(a[0:])
print(a[1:])
print(a[-0])
print(a[-1])
print(a[-2])
print(a[-3])
print(a[-4])